import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/Home.module.css";
import { Layout, Menu, Breadcrumb } from 'antd';
import { UserOutlined, LaptopOutlined, NotificationOutlined } from '@ant-design/icons';

const { Header, Content, Footer } = Layout;

const Home = () => {

  const { SubMenu } = Menu;
  const { Header, Content, Sider } = Layout;

  return (
    <Layout>
      <Head>
        <title>Crea Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header className="header">
      <Menu theme="dark" mode="horizontal"  defaultSelectedKeys={['2']}>
        <Menu.Item key="1"><img src="/logo_piccolo.png"/></Menu.Item>
        <Menu.Item key="2">nav 2</Menu.Item>
        <Menu.Item key="3">nav 3</Menu.Item>
      </Menu>
    </Header>
    <Content className="content">
      <div>Content</div>
    </Content>
    <Footer style={{ textAlign: 'center' }}>Ant Design ©2018 Created by Ant UED</Footer>
  </Layout>
  )
}


export default Home;
